# Generated by Django 3.0.3 on 2021-03-23 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MappedPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgcoordinate', models.TextField()),
                ('scanvalues', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='floorplan',
            name='plan',
            field=models.ImageField(upload_to=''),
        ),
    ]
