# Generated by Django 3.0.3 on 2021-04-06 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20210323_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappedpoint',
            name='plan',
            field=models.TextField(default='Default floorplan'),
        ),
    ]
