# Generated by Django 3.0.3 on 2021-04-08 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_mappedpoint_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='floorplan',
            name='aplist',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='floorplan',
            name='status',
            field=models.TextField(default='NEW'),
        ),
        migrations.AlterField(
            model_name='mappedpoint',
            name='plan',
            field=models.TextField(null=True),
        ),
    ]
