# Generated by Django 3.0.3 on 2021-04-23 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20210408_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floorplan',
            name='title',
            field=models.TextField(unique=True),
        ),
    ]
